### ISSUE TITLE
Should drug be blank or N/A for diagnostic/prognostic evidence?

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#115]
When adding new evidence for a diagnostic/prognostic variant there will be no drug. Should it be entered (and appear in GUI) as blank or 'N/A'. Currently we have a mix.

**Comment by jmcmichael** [comment]
My intention is to display N/A or hide that field completely if diagnostic or prognostic is selected from the evidence type menu. Any preference either way? I'm leaning slightly to N/A because it conveys slightly more information to the user (there could be a drug defined here, but it's not applicable for some reason), but on the other hand hiding it reduces the size of the form by one row.

**Comment by malachig** [comment]
I think I agree that N/A conveys more information...  But not a real strong opinion either way.
