### ISSUE TITLE
figure out what `closed` vs `rejected` is for suggested changes

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1157]
Suggested changes search has 2 statuses, closed and rejected. Apparently superseded is also in the database.

Why?

**Comment by acoffman** [comment]
I don't think we use superseded anymore, I'll double check. The initial use was if someone proposed a change to a field, and then someone else proposed a change to the same field, and the later one was accepted, the former one would be marked "superseded" as it was self evidently no longer valid, and it saved an editor from having to come in and manually close it.

I don't recall why we stopped doing that however.

**Comment by susannasiebert** [comment]
I would assume it's because one suggested change can cover multiple attributes so not all are necessarily superseded. 
Btw, `rejected` isn't a status for suggested changes; we only used `closed`. I think some folks would prefer to use `rejected` instead but I'm not sure if there is anything preventing us from using `rejected` instead.
