### ISSUE TITLE
Routing error while testing latest civic-server & civic-client

### ISSUE THREAD

**Issue by bwalsh** [genome/civic-client#126]
Hi:

Just doing a fresh integration test with latest civic-server & civic-client. Got the routing error below.  

Thanks,
-b

![image](https://cloud.githubusercontent.com/assets/47808/7949511/49b9c996-0943-11e5-9f5f-445a2ae3b284.png)

![image](https://cloud.githubusercontent.com/assets/47808/7949540/a62990da-0943-11e5-9cb9-2c232ebf516a.png)

### fresh clone of civic-server civic-client 
```
civic-server $ git log -1
commit f7126a2ae51c9df9094ab18eb1bf2a44954ab3e9
Author: Adam Coffman <acoffman@genome.wustl.edu>
Date:   Thu May 28 12:49:17 2015 -0500

civic-client $ git log -1
commit 9ac055a524248555a314052f518d0815e39bf762
Author: nspies13 <nspies13@gmail.com>
Date:   Thu Apr 16 00:07:20 2015 -0500
```

**Comment by jmcmichael** [comment]
Looks like your civic-client repo is out of date, the last commit on the master branch was yesterday (bf2a95cebb66befb5be39b1616da75de96138a0b). We've since switched to non-nested URLs for the REST endpoints, so if the variant ID is 1, to get its representation you'd request:

http://127.0.0.1:3000/api/variants/1

**Comment by jmcmichael** [comment]
Closing.

**Comment by bwalsh** [comment]
Thanks.  I double checked and was indeed on an older version. Apologies for the interruption
