### ISSUE TITLE
'Clinical Significance' is currently unpopulated when you edit evidence

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#129]
When I edit an evidence item, all other fields are pre-populated with their current value but 'ClinicalSignificance' is blank. 

![screen shot 2015-06-03 at 6 27 47 pm](https://cloud.githubusercontent.com/assets/856728/7973737/90a8e9fa-0a1e-11e5-9f7e-ef1130a3c566.png)

**Comment by jmcmichael** [comment]
Oops, I accidentally committed to master some work that I was doing to implement active forms (changing the options in the clinical significance select based on evidence type in this case). It's currently at a non-working state. I'll get this working tomorrow morning!

**Comment by jmcmichael** [comment]
Last night I misread and thought you were referring to the add evidence form, which I was working on in the afternoon. This is on the edit form however, and not related to the work I was doing.

When I view the edit form for an arbitrary evidence item, I see a populated/selected element for Clinical Significance, for example this one:

http://127.0.0.1:3001/#/events/genes/20/summary/variants/36/summary/evidence/136/edit/basic

Do you see the clinical significance specified for that record? Also, for which evidence item did you notice this behavior? It could be that it doesn't actually have a clinical significance assigned and that's why nothing is showing up.

**Comment by malachig** [comment]
Yeah, I could see it when I was viewing the evidence statement. I believe this field is required?  I'll see if I can find the example again.

**Comment by malachig** [comment]
Yeah I seem to be seeing this various places....

For example:
http://127.0.0.1:3001/#/events/genes/42/summary/variants/112/summary/evidence/356/edit/basic

It only seems to be missing when the `Clinical Significance` value for that evidence item is `Resistance Or Non-response`

**Comment by jmcmichael** [comment]
Aha, figured it out - if an evidence item's clinical significance is set to not applicable, the server returns 'N/a' instead of 'N/A' as it does for other fields. I can switch it on the client so that the form will highlight the N/A item, but it's probably better to ensure that we standardize on the same representation for not applicable for all fields.

Created a new issue issues on civic-server for this: genome/civic-server#62

**Comment by jmcmichael** [comment]
Also the same thing happens for Resistance or Non-response. This is b/c the server returns 'Resistance Or Non-response' and on the client I have that option specified as 'Resistance or Non-Response', so we just need to sync that on the client and server - updating the server issue.
