### ISSUE TITLE
Missing DO aliases

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1359]
Looking at EID2513, I tried to search for Bronchioloalveolar carcinoma but it didn't come up in the disease search. Due to the hyphen, the main name didn't match but I wonder why it didn't match an alias.

DOID:4926
Name:
Bronchiolo-alveolar Adenocarcinoma
--
Aliases:
Bronchioalveolar lung carcinoma [EXACT]
Bronchioloalveolar carcinoma [EXACT]
Minimally Invasive Lung Adenocarcinoma [EXACT]
--

**Comment by jsaliba10** [comment]
Quick note. None of the alias come up in the Civic disease search.

**Comment by susannasiebert** [comment]
There are currently no disease aliases for doid 4926 in our database. I will investigate why that is.

**Comment by susannasiebert** [comment]
DOID 4926 is not part of the https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/subsets/DO_cancer_slim.obo we import. I imagine it used to be, which is where the initial database entry came from but that DO entry has since been removed from the file. We don't have a mechanism in place for removing disease entries from out database that were removed from that file.

Edit to add: the next step would be to make a GitHub issue with DO to have this term re-added to the cancer_slim file.

**Comment by kkrysiak** [comment]
@susannasiebert Is there any way to make a quick comparison to find any other terms that may have been removed? I can put in a single github issue for all of them.

**Comment by susannasiebert** [comment]
There are quite a few (1772). I believe these came from the short time period where the cancer slim file was removed and we switched to the full cancer set.

**Comment by kkrysiak** [comment]
If we could get which of those 1772 are used vs not. It would be really great if suggested revisions containing these terms could also be evaluated. Otherwise, if those suggested changes are used, they will just be incorporated later.

**Comment by lschriml** [comment]
@kkrysiak - DOID:4926
Name: Bronchiolo-alveolar Adenocarcinoma is back in the slim.
