### ISSUE TITLE
Signed-out users are able to access the Add Evidence page, which displays the form w/ no Submit button

### ISSUE THREAD

**Issue by mkmatlock** [genome/civic-client#145]
No button:

![screen shot 2015-06-30 at 10 29 03 am](https://cloud.githubusercontent.com/assets/391221/8434747/e3c273c8-1f12-11e5-8eb8-a90118d8766c.png)

**Comment by mkmatlock** [comment]
I was definitely signed-in, actually.

**Comment by nspies13** [comment]
The problem was that we signed out of a different tab, without refreshing the current evidence tab. We were still on the add evidence form page from being signed in orignally, but didn't refresh to complete the sign out in the active tab, removing the Submit button, but still appearing as "signed in".

**Comment by mkmatlock** [comment]
Actually, I did reproduced this this morning, without signing out first. Same behavior.

**Comment by nspies13** [comment]
Gotcha.

**Comment by jmcmichael** [comment]
Add Evidence page now displays a 'Please create an account or sign in to add evidence' message to logged-out users that manage to load the page.
