### ISSUE TITLE
Add sentence to releases page to explain variant number discrepancy between VCF and TSV

### ISSUE THREAD

**Issue by susannasiebert** [genome/civic-client#1490]
"The VCFs only include variants with complete coordinates and, thus, the number of variants will be lower in the VCFs compared to the number of variants in the TSV."

or something to that effect

**Comment by kkrysiak** [comment]
I don't know the specifics of this. @ahwagner @obigriffith or @malachig can you assist in providing some text to add to the Data Releases page?

**Comment by malachig** [comment]
In order to comply with the VCF specification, the VCFs can only include variants with complete coordinates.  By contrast, the TSV variants file may contain variants with coordinates that have not been fully curated in CIViC. Additional variants are of types that can not be properly represented in VCF format.  Thus, the number of variants will be lower in the VCFs compared to the number of variants in the TSV.

**Comment by obigriffith** [comment]
Malachi's text sounds good
