### ISSUE TITLE
Issue with certain EIDs

### ISSUE THREAD

**Issue by arpaddanos** [genome/civic-client#1523]
The Evidence Items on this page generate a loading error and do not appear

https://civicdb.org/events/genes/5356/summary/variants/3202/summary#variant

**Comment by susannasiebert** [comment]
The error occurs because the disease used for the linked assertion (AID 35) no longer exists. I assume that this maybe is due to someone merging diseases but because the fix for https://github.com/griffithlab/civic-client/issues/1508 is not deployed yet, it didn’t move the assertion to the updated term.

The assertion text for AID 35 reads: `Loss of the SMARCB1 gene product INI1, assessed by monoclonal antibody is used to for diagnosis of Atypical Teratoid Rhabdoid Tumors (AT/RT). If loss of SMARCB1 or more rarely SMARCA4 is not observed, then WHO guidelines only a recommend a descriptive diagnosis of CNS embryonal tumour with rhabdoid features.`
Based on that, I suggest to assign the disease `Atypical Teratoid Rhabdoid Tumor` to this assertion.

Assertion 28 has a similar problem. Here the summary reads `IKZF1 deletions (both intragenic/partial and large deletions involving the entire gene) are associated with a poor prognosis in pediatric B-cell acute lymphoblastic leukemia (B-ALL), in terms of increased risk of relapse (RR) and decreased event‐free survival (EFS).` Based on that I would assign `B-cell Acute Lymphoblastic Leukemia` as the diease.

We also have several source suggestions with disease names that don’t match anything in our disease table. Not sure if we want to clean those up. If we do, the disease names used are:
```
 "Non-small Cell Lung Carcinoma",
 "Acute Lymphocytic Leukemia",
 "Lynch Syndrome (DOID: 3883)",
 "Anaplastic Thyroid Cancer",
 "Pediatric B-cell Lymphoblastic Leukemia"
```

**Comment by susannasiebert** [comment]
I'm planning on cleaning up the source suggestion disease as follows:
```
"Non-small Cell Lung Carcinoma" -> "Lung Non-small Cell Carcinoma"
"Acute Lymphocytic Leukemia" -> "Acute Lymphoblastic Leukemia"
"Lynch Syndrome (DOID: 3883)" -> "Lynch Syndrome"
"Anaplastic Thyroid Cancer" -> "Anaplastic Thyroid Carcinoma"
"Pediatric B-cell Lymphoblastic Leukemia" -> "Pediatric B-lymphoblastic Leukemia"
```

**Comment by susannasiebert** [comment]
These have been cleaned up. Resolving.
