### ISSUE TITLE
@ in evidence item hyperlinks to email

### ISSUE THREAD

**Issue by lsheta** [genome/civic-client#1561]
See [this EID](https://civicdb.org/events/genes/14303/summary/variants/2279/summary/evidence/6087/summary#evidence)

It looks like when @ is part of the text of an EID, a hyperlink is created.

**Comment by acoffman** [comment]
@jmcmichael, I poked around server side and it looks like the only place we do any markup preprocessing is for user comments, and the API response for the evidence description doesn't include the `mailto` link either, is this something happening on the angular side of things?

**Comment by jmcmichael** [comment]
Yeah, the evidence summary template runs the item's `description` text through AngularJS's ['linky' filter](https://docs.angularjs.org/api/ngSanitize/filter/linky), which identifies that gene name with an `@` symbol as an email address and creates a link out of it.

I think we apply that filter in order to support the inclusion of working URLs in these descriptions. Do we still want to support that, or was that an early feature that we can abandon? The API to that filter doesn't allow me to easily instruct it to abandon attempts to link email addresses.
