### ISSUE TITLE
variant tsv doesn't agree with interface

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1604]
The nightly TSV has 302 VHL variants while the interface has 684. This isn't ideal.

I have reasons to need this data but can derive it from other sources. ProteinPaint shows 430/445 variants which is also short, even accounting for variants without coordinates.

**Comment by susannasiebert** [comment]
The variant tsv only includes variants that have accepted evidence items. This behavior was requested (although it appears we didn’t make an issue for it) and implemented in https://github.com/griffithlab/civic-server/pull/624. It might be mentioned in our agenda. 

I believe this was changed because we wanted to ensure that the tsv only contain information reviewed by editors and to bring the variant tsv in line with the evidence item tsv which also only includes accepted evidence.

**Comment by kkrysiak** [comment]
Ohhh. Sorry, this makes sense. I didn't consider that this evening. We can resolve this.

**Comment by kkrysiak** [comment]
Yes one more reason I wholly endorse using the API and not the tsv downloads. I of all people should know better.
