### ISSUE TITLE
When a source is from ASCO, the journal is being resolved incorrectly

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#1612]
All ASCO sources should list: `Journal of Clinical Oncology` as their Journal.  Instead the ASCO ID is being used to pull the journal for the PubMed entry with that ID, leading to seemingly random journal assignments.  

e.g.
https://civicdb.org/sources/2862/summary

Resolves to a Journal: `Texas Medicine`.   Because the ASCO ID: https://meetinglibrary.asco.org/record/159508/abstract is pulling the journal from this unrelated paper in pubmed here: https://pubmed.ncbi.nlm.nih.gov/159508/

**Comment by susannasiebert** [comment]
I think this is leftover bad data from before we deployed this PR: https://github.com/griffithlab/civic-server/pull/588. The ASCO scraper doesn't set a `full_journal_title` so that field was never fixed. We will need to update the ASCO scraper to set this field correctly and manually update the ASCO entries in the database to the correct journal title.
