### ISSUE TITLE
Submitting a revision for review without changing any fields gives a confusing message

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#197]
I was adding representative transcripts to various variants and I was using this flow.
1.) Press the edit variant button
2.) In the variant edit form I would take notes of what I was about to do in the `Revision Description` field.
3.) Then I would add the new ensembl transcript id to the `Representative Transcript`
4.) Then hit `Submit revision for Review` button.

Everything works great.  But if I forgot to actually change something in step (3) I would get this error `409 - The attempted update conflicts with an existing record.`.

I agree this should be an error because I hadn't actually proposed any changes.  But could the error message say this instead?

**Comment by jmcmichael** [comment]
The server actually returns a helpful message 'No changes were suggested!', that I need to propagate up to the error message. At the moment I'm just paying attention to the HTTP error code 409, so all 409s will show the conflict message instead of the more helpful custom error message. I've been meaning to work on that (this is what issue #138 refers to), and I've put it at the top of my list.

**Comment by jmcmichael** [comment]
OK, this form and the other edit forms now return more detailed error messages from the server.
