### ISSUE TITLE
incorrect gene name causes 500 error

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#202]

**Comment by kkrysiak** [comment]
I tried to submit an evidence item and even though I typed the gene name correctly, I got the 500 error. When I saw this issue, I deleted the gene name and started typing it again, choosing it from the dropdown instead of typing it myself, which was successful.

<img width="1268" alt="screen shot 2015-10-01 at 1 55 22 am" src="https://cloud.githubusercontent.com/assets/8527125/10214674/15de910a-67e0-11e5-8a70-86ea9eed3f62.png">

**Comment by acoffman** [comment]
I wonder if this is a case where the structure of the form params is changing based on whether or not the autocomplete is used. Any guesses @jmcmichael?

**Comment by jmcmichael** [comment]
What was happening was that the form was allowing invalid field values to be submitted. What I've done to prevent this is to disable the submit button until the form has been properly filled out. A new message above the submit/cancel buttons will indicate whether there's any remaining issues with the form.

The gene field will flag an error unless it is filled w/ a value from the dropdown, so it should no longer be possible to submit the form with an invalid gene.

Right now the gene field doesn't show an error message for this, but I will add one so that it's clearer what the problem is and how to fix it.
