### ISSUE TITLE
In the 'Add variant group' form the variants field search is not performing as expected.

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#251]
For example, you can't find REL variants if you start by typing REL, however, if you type 'Amplification', the REL - Amplification variant appears. Same goes for NPM1 and I'm sure others.

**Comment by jmcmichael** [comment]
Currently this is expected behavior, although it might not be intuitive. The endpoint I'm using is filtering only on variants. The response includes the entrez name, and I just add it to the the dropdown row in order to help differentiate between variants with the same name but different genes.

I can filter on multiple attributes but it'll apply the filter to variants AND genes, whereas what you want to do is apply it to variants OR genes. This could be easy as adding a boolean query attribute that will allow me to specify whether I want the filters applied as an AND operation or an OR operation, @acoffman what do you think?

**Comment by kkrysiak** [comment]
I think having the ability to search on gene name or variant name will be helpful in the sense that someone could create a variant group from any page and not necessarily need to know the name of the variant if they know the gene of interest. I might not think of adding both exon 12 and W288fs (which is in exon 12) if I'm not on that page. 

It's not a big deal but when I was creating some documentation I realized I liked the idea of creating a variant group from anywhere. We could just as easily specify the search behavior to the user in the documentation if this is a pain to implement.

**Comment by jmcmichael** [comment]
Yeah, I think you're right - it would be better to implement the Add Variant Group page as its own page instead of implicitly linked with a specific gene's variants. I'm not sure where I would put other links to it, though - the variant menu seems like a really good place but I can't immediately think of another place where it would be good to go.

**Comment by kkrysiak** [comment]
I think having the ability to get to it from any gene page like it is now is quite handy. If we figure out a way to implement a table view for the variant groups, that would be the other place I would add it. I agree, right now there isn't another intuitive place to add it. We should definitely add it to the help page as well but again, that's not really an intuitive access point either, just a convenient one.

**Comment by jmcmichael** [comment]
OK, I'll implement this as a freestanding page, and auto-fill the gene from the Add Variant Group button in the sidebar.
