### ISSUE TITLE
show new variant names in all caps on the Add Evidence form

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#273]
I added a new variant and used lowercase letters. These have been maintained. I'm not sure if this is expected behavior. I think all the original imported variants were forced to be all caps.

![screen shot 2015-11-12 at 12 03 26 pm](https://cloud.githubusercontent.com/assets/8527125/11126697/bed2119e-8935-11e5-8514-c50724121bcf.png)

**Comment by jmcmichael** [comment]
We don't currently enforce all-caps when submitting an evidence item with new variants. I discussed this with Adam and we decided it would be a good idea to enforce this convention since the import script converts to all-caps. He'll implement the conversion on the server-side and I'll ensure that the variant input element shows only capitals.

**Comment by acoffman** [comment]
All caps are now enforced on the backend. New variant names will be upcased before storing them in the db.

**Comment by jmcmichael** [comment]
To force the variant field to all-caps on the client requires angular-formly issue #494 to be fixed: https://github.com/formly-js/angular-formly/issues/494
