### ISSUE TITLE
Add edit button to variant coordinates box

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#286]
Takes you to the same edit variant page, just auto scrolls you to the coordinates section. This will help emphasize the fact that this is editable in contrast to the MyGeneInfo section above.

**Comment by malachig** [comment]
Yeah currently the visual cue is maybe that info from MyGene.info is created by CIViC and not editable, but the variant coordinate info is a separate thing. 

Since determining variant coordinates is kind of a distinct (and critical, time consuming) creation activity, maybe having an edit button right there by the variant coordinates will help convey that these things are manually determined and reviewed.
