### ISSUE TITLE
Default behavior for rejected evidence items should be to not show them

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#294]
A couple minor issues with rejected evidence items in the live site.

- It seems like the default behavior is currently to show them. Even when not logged in, we see them.
- The default filtering should probably be to show accepted evidence only. 
- If you are logged in, perhaps show pending as well.
- Only show rejected if you actively select this option during your session.

Also the selection of filtering options doesn't seem to be working as expected.  After a page reload, all items are shown.  If I select `Show Rejected` the rejected item disappears.  But the `Show Rejected` option is still highlighted.  Now if I try to toggle it again, the rejected evidence item does not reappear.  But if I select one of the other two options, such as `Show Accepted` the rejected item reappears.

**Comment by malachig** [comment]
On further investigation this is not as simple to reproduce...  Here is the example I was playing around with:
https://civic.genome.wustl.edu/#/events/genes/19/summary/variants/253/summary#variant

It seems like maybe things get into a weird state when I select `Clear all filters`.  I works more smoothly up to that point...

**Comment by jmcmichael** [comment]
Currently I have the grid set to show rejected items only if there are no approved or pending items to show, figuring that it's better to show rejected items instead of a blank grid. However, now that you've brought this up I'm thinking maybe changing the behavior of the grid based on the number and type of items available causes more confusion than it solves. So I'll go ahead and implement the behavior that you've described.

The `Clear all filters` selection isn't working as expected, I'm looking into that now.

**Comment by jmcmichael** [comment]
Also, 'Show Rejected' will be toggled on if the evidence item requested for the evidence view is actually a rejected item (otherwise the grid would not be able to show the active highlighted row).

**Comment by jmcmichael** [comment]
I've updated the grid menu with the following behavior:

- grid only shows approved and pending items by default
  - unless the requested view is for a rejected evidence item (we need to show the highlighted item in the grid)
- grid menu Show Rejected item does nothing and prints a console warning if current item is rejected ('Cannot hide rejected items if currently selected item is itself rejected.'). This message is probably best displayed with some UI message, but I haven't yet implemented a global message system.

I can easily hide pending items from logged-out viewers, but I'm thinking that perhaps we should still show those as it gives viewers an idea of the process by which items become approved for inclusion in CIViC. What are the compelling reasons to hide pending items from logged-out viewers?

**Comment by malachig** [comment]
This all seems sensible to me.

**Comment by jmcmichael** [comment]
Ok, cool I'll close this issue.

NOTE: The odd behavior of the 'Clear all filters' selection unfortunately looks like a bug with ui-grid (see angular-ui/ui-grid#4657). I'm trying to figure out how to modify its behavior or hide the element but it's not looking promising, so we may have to wait until the bug is fixed or get to mucking around with ui-grid's internals and submitting a PR-request ourselves.

I've added a client issue to track this bug: genome/civic-client#295
