### ISSUE TITLE
Auto-fill information from previous variant page when adding evidence items

### ISSUE THREAD

**Issue by nspies13** [genome/civic-client#31]
It would save quite a bit of effort to pre-populate the add evidence form with information from the previous page. This could be Gene, Entrez ID, and Variant

**Comment by jmcmichael** [comment]
I've moved this button from the Evidence tabs to the subheader, so this issue is somewhat moot.

I can still capture the current page's gene/variant IDs if they're on an event page and pre-populate the form based on that, but I'm not totally sure that's what users would expect from clicking a button in the header. Please reopen if you want to discuss further.
