### ISSUE TITLE
AR (gene) can't be reached using the type ahead search

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#341]
I'm not sure that there will be many instances like this, but if you can't navigate to AR using the quick search box. When you are trying to go to AR - Overexpression, you can't without using the browse page.

**Comment by malachig** [comment]
Interesting.  Variants of it can be if you know in advance what they are...

**Comment by kkrysiak** [comment]
In the case of overexpression, there are too many other genes that have overexpression as a variant.

**Comment by acoffman** [comment]
So, what seems to be going on here is a matter of ordering.

Since the typeahead search searches many things (gene names, variant names, disease names, etc), we just rank the results by number of characters matched and then take the top `n` of them (I think its 12). If you search for `ar` you'll see that every result does match 'ar' somewhere, its just such a short string that it matches a ton of things and the gene `AR` doesn't end up in the top `n` results.

Should we give higher precedence to Gene matches? That would have the effect of making it harder to find things by other fields in the typeahead, but maybe Genes are the most natural item a person might search for in that field?

**Comment by malachig** [comment]
It is the thing I am most commonly searching for.  Really wish HUGO enforced a minimum 4 character name length.  Maybe would should try giving precedence to Gene matches and see how it compares.

**Comment by kkrysiak** [comment]
Another option would be to prioritize beginning of string matches, perhaps?

**Comment by obigriffith** [comment]
Disease and drug names tend to be much longer and specific. So, if you are searching for lymphoma or fluorouracil you won't have a problem. I suggest we prioritize to gene matches, then synonym matches, then variant matches, then others. If that is possible.

**Comment by acoffman** [comment]
Yeah, that should be possible to do!

**Comment by acoffman** [comment]
Fixed in master and will go out in the next release!
