### ISSUE TITLE
Browsing by gene would be nice, clicking could open up top variant for that gene. 

### ISSUE THREAD

**Issue by nspies13** [genome/civic-client#35]
Collapsing the variants on the browse page to allow for a unique list of genes may be nice for people searching for a specific gene but not variant.

**Comment by jmcmichael** [comment]
I'm not sure I understand - by collapsing the variants, do you mean adjusting the data grid so it doesn't show more than a single row for each gene, and to list the variants in a single cell?

Also, if the use case is someone searching for a Gene, couldn't they use the gene filter box?

**Comment by nspies13** [comment]
I agree. Let’s punt on this. Revisit it when more important matters have been addressed.

**Comment by jmcmichael** [comment]
I'll go ahead and close this. The datagrid supports grouping, so I can look into that later if the current grid layout warrants it.

**Comment by malachig** [comment]
Yes, the gene data grid would show all of the variants collapsed to a single row for each gene. Or it could simply report the number of variants for each gene (again one row per gene).  

Yes, you can search for a gene of interest or filter down to a single gene on the existing table.  But currently there is no way in CIViC to get a sense of how many genes are covered by CIVIC overall.  And how many variants of these genes?  This is something that many will want to see to get a sense of the scope/size of data in CIVIC at the level of genes (the unit, many people will be thinking of).  

In order to get a sense of this now, you need to enter every gene one by one and mentally keep track of the number of rows that come back for each.

Once implemented, if you click on one of the gene rows it could just take you to the existing variant/event summary view for an arbitrary variant of that gene (by default, the one with the most evidence statements perhaps could be initially selected).  Then the user can start browsing variants of that gene.

In terms of navigation we could have 'browse variants' and 'browse genes' that took you to the two versions of the browse data grid.

**Comment by malachig** [comment]
I agree that this is not a short term high priority, but I think the need is high enough that we should leave this issue open for further discussion.

**Comment by jmcmichael** [comment]
Is this issue more about giving users a sense of the scale of the CIViC database, or addressing user navigation/search use cases that are not provided by the Browse datagrid? I agree that we should give users a sense of the size of the db, *and* that we have unmet needs regarding navigation/search, but we're kind of mixing up the two problems in this issue.

I would like to split this into two issues - one that addresses a different use case for the Browse grid (searching by gene w/ clear feedback on # of variants per gene) and another that addresses giving users a sense of scale of the db.

If we want to give users a sense of the scale of the CIViC database, we can just provide them with the gene/variant counts on the homepage or around the browse datagrid itself.

If we want to group variants by gene in the Browse view, I can also work with the datagrid to see how this might be possible (using the grouping features of the grid seem like a good start).

**Comment by malachig** [comment]
Its not about the number of genes (although those kind of summaries would be great), it is more about the identity of those genes.  Right now I can not tell what genes are covered in CIViC without searching one-by-one for every possible gene or flipping through pages of variants and mentally building a unique list of genes, how many variants were found for each, etc.

**Comment by obigriffith** [comment]
I agree these are two issues. Summary stats of the numbers of genes, variants, evidence statements, and sources are a no-brainer that we should definitely have on the front page, side, bar or somewhere. But, as Malachi says there is also a specific (desirable) functionality to being able to easily browse through the current list of covered genes. For many people that will be the primary entry point. But, I'm not certain what the right mechanism for it is. Two layers of browse table views. Start at gene list, then get to variant list?

**Comment by jmcmichael** [comment]
Do you think that your use case would be covered by a browse datagrid that could be switched between a browse-by-gene and browse-by-variant versions?

Browse by variant would show one variant per line, as we do now, and browse by gene would show one gene per line with variants aggregated into a cell or something similar.

**Comment by nspies13** [comment]
I think that is a good idea. It would be important to make the two options clear. 

Nick

**Comment by jmcmichael** [comment]
OK, a browse grid w/ two modes is relatively straightforward to implement.

**Comment by malachig** [comment]
Yes, I think the dual mode datagrid the way you describe it would fantastic.

**Comment by malachig** [comment]
Content of a gene level view that I think would be nice from a user perspective:

| Gene Symbol | Gene aliases | Variants (and count) | Evidence statements | 
| ------------------ | ------------------ | --------------------------- | ---------------------------- |
| ERBB2           | Her2, etc.      | V12G, R123L, etc.    | 25                               |

**Comment by acoffman** [comment]
We don't currently have any gene alias information locally. We pretty much gave up tracking gene metadata beyond entrez id and symbol, and embeds the MyGene.info data into the page. Are gene aliases something we'll want to begin storing and curating in civic?

**Comment by nspies13** [comment]
So this may be a hacky, band-aid type fix. But really the most common gene that would be referred to by its synonym is HER2/ERBB2. Could we support searching ERBB2 variants by typing "HER2"? Or should we pull in all the synonyms?

**Comment by jmcmichael** [comment]
OK, I've implemented a browse page that supports both browsing by variant, and browsing by gene. The server endpoint for browsing currently doesn't provide aliases for the genes, but that probably wouldn't be an issue. ([I've created an issue over in civic-server asking for gene aliases in the /variants endpoint.](https://github.com/genome/civic-server/issues/39))

Adding in a variant list column seems a bit pointless since most genes have far more variants than will fit in a cell. But I can do it and provide a tooltip rollover. For now we just have a variant count.

I'll leave this issue open until we're all satisfied with the new modes. Please let me know how these work for you.

**Comment by obigriffith** [comment]
We don't want to curate gene synonyms and I'm not in favor of a Her2 only solution. But, it is a very common use case that someone wants to search for a gene and uses a synonym.

**Comment by malachig** [comment]
@nspies13 I think we should have all synonyms.  Entrez has already invested huge resources in curating these for us.  Any name that might be used by clinicians will in all likelihood already be covered by them.  Since we can get these easily from Entrez, we can immediately handle all the ambiguities in one shot.  

@jmcmichael the 'Browse by Gene' tab looks fantastic!  This is pretty much exactly what I was imagining.  Once we get the synonyms in there I think this resolves several suggestions all at once.

**Comment by acoffman** [comment]
This is done in b88e06c3b834a1abc77b4a76e1e0c36120bb5d56. You'll need to reimport to slurp in the new aliases. I've also added support server side for searching aliases in 818cce298269efd76c506accc9275e48ff3a2cbe and it appears to be working seamlessly in the quicksearch window.

**Comment by jmcmichael** [comment]
I've added aliases to the browse by gene grid and quick search box in 5d46462ffd948180f33538eacf0093903ca1f3fb.

**Comment by jmcmichael** [comment]
Done.
