### ISSUE TITLE
Some of the Variant Groups have strange display behaviors

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#38]
A greyed out "Summary" tab is displaying at the top of the page when I click on some Variant Group summaries such as these.
http://0.0.0.0:3001/#/events/genes/25/summary/variant-groups/1/summary (See screenshot below)
http://0.0.0.0:3001/#/events/genes/238/summary/variant-groups/3/summary

But not others:
http://0.0.0.0:3001/#/events/genes/238/summary/variant-groups/2/summary

![screen shot 2015-02-24 at 10 24 34 am](https://cloud.githubusercontent.com/assets/8527125/6353501/5d206f16-bc0f-11e4-8618-3f4f3b6a99a9.png)

**Comment by jmcmichael** [comment]
Yeah, the title wraps if the state title is longer than the space allocated for it. I've updated the styles to clip these wrapped lines so you just won't see the second line, that was pushed a few commits ago so it should be live now.

I have a better fix for this in mind that will reduce the font size so that the line fits, but will wait to implement that until later.
