### ISSUE TITLE
Username appears as camelCase and when referenced as displayed in a comment failure to connect to proper user handle

### ISSUE THREAD

**Issue by bainscou** [genome/civic-client#389]
See NickSpies.

![screen shot 2016-03-31 at 6 15 11 pm](https://cloud.githubusercontent.com/assets/1072436/14193698/ad5dd650-f76c-11e5-83b2-f2f9612eb3c9.jpg)

I replicated this format in my comment "@NickSpies" and it does not appear to link correctly to Nick's user page.

See RID1441

**Comment by obigriffith** [comment]
I can't get to Nick's profile page at all right now. I think it should be at: https://civic.genome.wustl.edu/#/users/41/profile but it doesn't load.

**Comment by kkrysiak** [comment]
His user page has been having problems, this came up in a recent meeting. The mention for my username in that same comment worked perfectly but my username doesn't use camelcase either. I thought about changing it but the case is probably not the issue here. It does make me wonder what happens to the previous mentions if I change my user name.

**Comment by acoffman** [comment]
This fixed on both counts (both the profile linking and the camel casing).
