### ISSUE TITLE
increase height of event revisions grid to 4 or 5 rows

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#509]

**Comment by malachig** [comment]
Went to submit this issue again and found that this issue already exists.  

I find it disorienting how tiny this grid is.  At present only two rows are shown.  As we get more revisions, increasingly you need to see the contents of this table.  It is hard to scroll up and down and see what is happening because it feels like you are seeing this thin slice of the contents.  

I think this grid should display at least 3 rows, possibly 4 or 5.  It is only shown when an editor goes to the talk page so it generally wont make the view longer for consumers of CIViC, just make things a bit easier for curators/editors.

Example,

https://civic.genome.wustl.edu/#/events/genes/11335/summary/variants/276/summary/evidence/704/talk/revisions/list/1038/summary#evidence

![screen shot 2017-02-06 at 11 31 41 am](https://cloud.githubusercontent.com/assets/856728/22658488/e13dba56-ec5f-11e6-9876-deb7de9b482d.png)

**Comment by jmcmichael** [comment]
OK, updated revision grid to show 5 rows:

![screen shot 2017-02-06 at 1 13 35 pm](https://cloud.githubusercontent.com/assets/132909/22662315/2364b318-ec6e-11e6-82e6-8cb75b9c8afc.png)
