### ISSUE TITLE
users should be able to edit and delete their own posts

### ISSUE THREAD

**Issue by nspies13** [genome/civic-client#54]
Once I submit an edit with a typo, I had to go to admin, delete it, and remake a new one. Editing and Deleting comments would be nice.

**Comment by jmcmichael** [comment]
Yup, definitely. Marking this as an enhancement.

**Comment by jmcmichael** [comment]
Should they be able to edit/delete their own posts indefinitely or should we put a time limit on that ability, as many forums now do?

**Comment by nspies13** [comment]
Time limits are good, but are they a hassle to implement?

**Comment by jmcmichael** [comment]
No it wouldn't be a hassle on the UI and I doubt they would be much of a hassle on the backend either.

I bring this up because when people are debating in a forum based on each other's messages, it can become problematic if authors can go back and edit their original messages, because the replies to that message may no longer make sense to future readers if the original author changes the content of their comment drastically or alters their arguments based on subsequent discussion. Time limits on editing help mitigate this problem.

**Comment by jmcmichael** [comment]
Users can now delete comments. Editing will take a bit more UI work - I'll add that as a new issue.
