### ISSUE TITLE
Match HGVS expressions between myvariant.info and internal representation

### ISSUE THREAD

**Issue by ahwagner** [genome/civic-client#715]
Sometimes we don't have an internal representation for a variant, but myvariant.info does.

e.g. BRAF V600E:
<img width="942" alt="screen shot 2017-03-24 at 3 52 44 pm" src="https://cloud.githubusercontent.com/assets/811065/24313302/4897b8fa-10aa-11e7-9994-af204194bc2c.png">

Sometimes we have an internal representation for a variant, but it uses different nomenclature than myvariant.info (e.g. "NC_000007" instead of "chr7" in BRAF V600D):

<img width="942" alt="screen shot 2017-03-24 at 3 56 26 pm" src="https://cloud.githubusercontent.com/assets/811065/24313394/a1b79856-10aa-11e7-83d0-f39256c4d743.png">

**Comment by malachig** [comment]
This is by design. There are many possible HGVS expressions.  And there is not a clear one-to-one relationship between the CIViC concept of a variant and ClinVar's concept of a variant.  In some simple cases, the versions will match up okay (at the genome level mostly).  

The HGVS field shown on the left, is there to allow us flexibility to define our own HGVS expressions.  We may put quite a few there (genome, cDNA, and protein for example, multiple genome builds, multiple transcript isoforms, ensembl transcripts, etc.).  This is a major area of curation, therefore we need the ability to create our own suggestions.  My variant info data is shown only for reference and we have no ability to control, modify, or update it.  It is just there as a helper along with a lot of other supporting information from unverified (by civic curators) external sources.

**Comment by malachig** [comment]
Indeed in the example you screenshot above, V600E, there are currently three HGVS expressions that will be shown as soon as an editor finds time to review them.  :).  Including an genome HGVS similar to the one from myvariant.info (but with the more correct usage of a real sequence accession):

NC_000007.13:g.140453136A>T
NM_004333.4:c.1799T>A
NP_004324.2:p.Val600Glu

The first of these is from the civic bot (one of hundreds currently awaiting editor review and approval). The other two were created by Lynzey (who also has a couple hundred pending revisions awaiting review).
