### ISSUE TITLE
Users should be warned not to enter data that could compromise patient privacy?

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#72]
This should be obvious but since we are working with clinical interpretations that could involve n-of-1 studies, case reports, patient anecdotes...   While we require that data come only from published papers this should not be an issue.

However, just to be totally clear, maybe in the interface where users add new evidence they should be reminded that data constituting protected health information (PHI) should not be entered.

Where PHI is defined here for the US by HIPAA:
http://www.hipaa.com/hipaa-protected-health-information-what-does-phi-include/

For Canada by PIPEDA:
http://laws-lois.justice.gc.ca/PDF/P-8.6.pdf

Etc.

**Comment by jmcmichael** [comment]
Yeah we can definitely add this to the instructions block at the top. Can you give me a draft statement that's as short as possible while still covering the important points? We could keep more detailed information in a glossary definition of PHI that links to the relevant statutes for various jurisdictions.

Maybe something like:

'Data constituting protected health information (PHI) should not be entered. Please familiarize yourself with your jurisdictions definition of PHI before contributing.'

With 'jurisdiction's definition of PHI' linked to the PHI definition in the glossary, which contains links to the HIPAA and PIPEDA documents.

**Comment by malachig** [comment]
That sounds good to me!

**Comment by jmcmichael** [comment]
I was just thinking that this issue might not be clear. These questions occurred to me:

- should CIViC strive to conform to the HIPAA guidelines of the jurisdiction where it is served and supported (US), or conform to some set of HIPAA guidelines from the jurisdicitons of contributing researchers?
- is it even possible to abide by the HIPAA guidelines of many different jurisdictions?
- should we pick the strictest guidelines from contributing jurisdictions and seek to abide by that in order to have a dataset that can be easily used in any jurisdiction w/o risk of legal exposure?

Maybe the HIPAA guidelines have been written to answer these questions, I'm not very familiar with the statutes or how much effort has gone into standardizing the various medical privacy laws internationally.

**Comment by obigriffith** [comment]
CIViC is meant for curation of only published statements so really there is no reason that anything remotely like PHI should be uploaded since that should be caught and prevented at the point of publication. However, since we do have a somewhat free-form entry it is theoretically possible. We can lean towards the strict end of any laws.

**Comment by malachig** [comment]
Basically, do not put phone numbers, home addresses, SSNs, etc. into the interface.  We just want to say this so that we can say that we did.  And to demonstrate that we have thought of it.  

Being in the US we are responsible for adhering to HIPAA.  It would be surprising if someone entered PHI (by any definition) into the interface, but it technically possible ...  Our strategy could be to warn users (1st line of defense), and then it will be the responsibility of the admins to check each record before approving its addition (2nd line of defense).

**Comment by jmcmichael** [comment]
OK, yeah makes sense - I was kinda overthinking it.

**Comment by jmcmichael** [comment]
OK, I added 'Data constituting protected health information (PHI) should not be entered. Please familiarize yourself with your jurisdictions definition of PHI before contributing.' to the Explanation field's help text, and also to the specifications spreadsheet.
